const services = [
  {
    Icon: Wrench,
    title: "Toy Repair",
    desc: "Full repair for ride-on cars, RC toys, bikes and scooters & hover board of all brands.",
    accent: "from-orange-500/18 to-amber-400/10",
    iconBg: "from-orange-500/20 to-amber-400/12",
    iconBorder: "border-orange-400/20",
    iconColor: "text-orange-500",
  },
  {
    Icon: BatteryCharging,
    title: "Battery Replacement",
    desc: "Replace old batteries with reliable, child-safe power solutions.",
    accent: "from-green-500/15 to-emerald-400/8",
    iconBg: "from-green-500/18 to-emerald-400/10",
    iconBorder: "border-green-400/20",
    iconColor: "text-green-600",
  },
  {
    Icon: Settings2,
    title: "Maintenance",
    desc: "Regular servicing for longer life and consistently better performance.",
    accent: "from-blue-500/15 to-sky-400/8",
    iconBg: "from-blue-500/18 to-sky-400/10",
    iconBorder: "border-blue-400/20",
    iconColor: "text-blue-600",
  },
  {
    Icon: Truck,
    title: "Pickup & Drop",
    desc: "Convenient doorstep pickup and drop service across Bangalore.",
    accent: "from-purple-500/15 to-violet-400/8",
    iconBg: "from-purple-500/18 to-violet-400/10",
    iconBorder: "border-purple-400/20",
    iconColor: "text-purple-600",
  },
];
